version: '0.1'

services:
  backend:
    build: ./backend
    container_name: "backend-app"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - TZ=Asia/Seoul
    networks:
      custom:
    depends_on:
      - db
    env_file:
      - ./backend/.env
    stdin_open: true
    tty: true
    # restart: on-failure

  db:
    image: postgres:14-alpine
    container_name: "db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      custom:
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=hts
      - TZ=Asia/Seoul
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  # node-modules:

networks:
  custom:
    ipam:
      config:
        - subnet : 172.19.0.0/16
          gateway : 172.19.0.1
